package com.example.we_muslim20.data

object AllData {
    val hijaiyah = arrayOf(
        "اللَّه",
        "الرَّحْمَنُ",
        "الرَّحِيْمُ",
        "المَلِكُ",
        "القُدُّوْسُ",
        "السَّلَامُ",
        "المُؤْْمِنُ",
        "المُهَيْمِنُ",
        "العَزِيْزُ",
        "الجَبَّارُ",
        "المُتَكَبِّرُ",
        "الخَالِقُ",
        "البَارِئُ",
        "المُصَوِّرُ",
        "الغَفَّارُ",
        "القَهَّارُ",
        "الوَهَابُ",
        "الرَّزَّاقُ",
        "الفَتَّاحُ",
        "العَلِيْمُ",
        "القَابِضُ",
        "البَاسِطُ",
        "الخَافِضُ",
        "الرَّافِعُ",
        "المُعِزُّ",
        "المُذِلُّ",
        "السَّمِيعُ",
        "البَصِيرُ",
        "الحَكَمُ",
        "العَدْلُ",
        "اللَّطِيْفُ",
        "الخَبِيرُ",
        "الحَلِيمُ",
        "العَظِيْمُ",
        "الغَفُوْرُ",
        "الشَّكُوْرُ",
        "العَلِيُّ",
        "الكَبِيْرُ",
        "الحَفِيْظُ",
        "المُقِيْتُ",
        "الحَسِيْبُ",
        "الجَلِيْلُ",
        "الكَرِيْمُ",
        "الرَّقِيْبُ",
        "المُجِيْبُ",
        "الوَاسِعُ",
        "الحَكِيْمُ",
        "الوَدُوْدُ",
        "المَجِيْدُ",
        "البَاعِثُ",
        "الشَّهِيْدُ",
        "الحَقُّ",
        "الوَكِيْلُ",
        "القَوِيُّ",
        "المَتِيْنُ",
        "الوَلِيُّ",
        "الحَمِيْدُ",
        "المُحْصِى",
        "المُبْدِئُ",
        "المُعِيْدُ",
        "المَحِيْى",
        "المُمِيْتُ",
        "الحَيُّ",
        "القَيُّوْمُ",
        "الوَاجِدُ",
        "المَاجِدُ",
        "الوَاحِدُ",
        "الاَحَدُ",
        "الصَّمَدُ",
        "القَادِرُ",
        "المُقْتَدِرُ",
        "المُقَدِّمُ",
        "المُؤَخِرُ",
        "الأَوَّلُ",
        "الأَخِرُ",
        "الظَّاهِرُ",
        "البَاطِنُ",
        "الوَالِي",
        "المُتَعَالِي",
        "البَرُّ",
        "التَّوَابُ",
        "المُنْتَقِمُ",
        "العَفُوُّ",
        "الرَّؤُوفُ",
        "مَالِكُ المُلْكِ",
        "ذُو الجَلَالِ وَ الإِكْرَامُ",
        "المُقْسِطُ",
        "الجَامِعُ",
        "الغَنِىُّ",
        "المُغْنِى",
        "المَانِعُ",
        "الضَّارُ",
        "النَّافِعُ",
        "النُّوْرُ",
        "الهَادِئُ",
        "البَدِيْعُ",
        "البَاقِي",
        "الوَارِثُ",
        "الرَّشِيْدُ",
        "الصَبُورُ"
    )

    val namaAsmaulHusna = arrayOf(
        "Allahu",
        "Ar Rahmanu",
        "Ar Rahiimu",
        "Al Maliku",
        "Al Quddusu",
        "As Salaamu",
        "Al Mu`minu",
        "Al Muhaiminu",
        "Al `Aziizu",
        "Al Jabbaru",
        "Al Mutakabbiru",
        "Al Khaliqu",
        "Al Baariu",
        "Al Mushawwiruu",
        "Al Ghaffaaru",
        "Al Qahhaaru",
        "Al Wahhaabu",
        "Ar Razzaaqu",
        "Al Fattaahu",
        "Al `Aliimu",
        "Al Qaabidhu",
        "Al Baasithu",
        "Al Khaafidhu",
        "Ar Raafiu",
        "Al Mu`izzu",
        "Al Mudzilu",
        "Al Samiiu",
        "Al Bashiiru",
        "Al Hakamu",
        "Al `Adlu",
        "Al Lathiifu",
        "Al Khabiiru",
        "Al Haliimu",
        "Al `Azhiimu",
        "Al Ghafuuru",
        "As Syakuuru",
        "Al `Aliyu",
        "Al Kabiiru",
        "Al Hafizhu",
        "Al Muqiitu",
        "Al Hasiibu",
        "Al Jaliilu",
        "Al Kariimu",
        "Ar Raqiibu",
        "Al Mujiibu",
        "Al Waasi`u",
        "Al Hakimu",
        "Al Waduudu",
        "Al Majiidu",
        "Al Baa`itsu",
        "As Syahiidu",
        "Al Haqqu",
        "Al Wakiilu",
        "Al Qawiyyu",
        "Al Matiinu",
        "Al Waliyyu",
        "Al Hamiidu",
        "Al Muhshii",
        "Al Mubdi`u",
        "Al Mu`iidu",
        "Al Muhyii",
        "Al Mumiitu",
        "Al Hayyuu",
        "Al Qayyuumu",
        "Al Waajidu",
        "Al Maajidu",
        "Al Wahidu",
        "Al Ahadu",
        "As Shamadu",
        "Al Qaadiru",
        "Al Muqtadiru",
        "Al Muqaddimu",
        "Al Mu`akkhiru",
        "Al Awwalu",
        "Al Aakhiru",
        "Az Zhaahiru",
        "Al Baathinu",
        "Al Waali",
        "Al Muta`aalii",
        "Al Barru",
        "At Tawwaabu",
        "Al Muntaqimu",
        "Al Afuwwu",
        "Ar Ra`uufu",
        "Malikul Mulku",
        "Dzul Jalaali Wal Ikraamu",
        "Al Muqsithu",
        "Al Jamii`u",
        "Al Ghaniyyu",
        "Al Mughnii",
        "Al Maani`u",
        "Ad Dhaaru",
        "An Nafii`u",
        "An Nuuru",
        "Al Haadiiu",
        "Al Badii’u",
        "Al Baaqiiu",
        "Al Waaritsu",
        "Ar Rasyiidu",
        "As Shabuuru"
    )

    val terjemahanAsmaulHusna = arrayOf(
        "Allah",
        "Yang Maha Pengasih",
        "Yang Maha Penyayang",
        "Yang Maha Merajai / Memerintah",
        "Yang Maha Suci",
        "Yang Maha Memberi Kesejahteraan",
        "Yang Maha Memberi Keamanan",
        "Yang Maha Pemelihara",
        "Yang Maha Mulia",
        "Yang Maha PerkasaYang Maha Perkasa",
        "Yang Memiliki Mutlak Kegagahan",
        "Yang Maha Megah, Yang Memiliki Kebesaran",
        "Yang Maha Pencipta",
        "Yang Maha Melepaskan (Membuat, Membentuk, Menyeimbangkan)",
        "Yang Maha Membentuk Rupa (makhluknya)",
        "Yang Maha Pengampun",
        "Yang Maha Menundukan",
        "Yang Maha Pemberi Karunia",
        "Yang Maha Pemberi Rezeki",
        "Yang Maha Pembuka Rahmat",
        "Yang Maha Mengetahui (Memiliki Ilmu)",
        "Yang Maha Menyempitkan (makhluknya)",
        "Yang Maha Melapangkan (makhluknya)",
        "Yang Maha Merendahkan (makhluknya)",
        "Yang Maha Meninggikan (makhluknya)",
        "Yang Maha Memuliakan (makhluknya)",
        "Yang Maha Menghinakan (makhluknya)",
        "Yang Maha Mendengar",
        "Yang Maha Melihat",
        "Yang Maha Menetapkan",
        "Yang Maha Adil",
        "Yang Maha Lembut",
        "Yang Maha Mengenal",
        "Yang Maha Penyantun",
        "Allah Yang Maha Agung",
        "Allah Yang Maha Memberi Pengampunan",
        "Allah Yang Maha Pembalas Budi (Menghargai)",
        "Allah Yang Maha Tinggi",
        "Yang Maha Besar",
        "Allah Yang Maha Memelihara",
        "Allah Yang Maha Pemberi Kecukupan",
        "Allah Yang Maha Membuat Perhitungan",
        "Allah Yang Maha Luhur",
        "Allah Yang Maha Pemurah",
        "Allah Yang Maha Mengawasi",
        "Allah Yang Maha Mengabulkan",
        "Allah Yang Maha Luas",
        "Allah Yang Maha Bijaksana",
        "Allah Yang Maha Mengasihi",
        "Allah Yang Maha Mulia",
        "Allah Yang Maha Membangkitkan",
        "Allah Yang Maha Menyaksikan",
        "Allah Yang Maha Benar",
        "Allah Yang Maha Memelihara",
        "Allah Yang Maha Kuat",
        "Allah Yang Maha Kokoh",
        "Allah Yang Maha Melindungi",
        "Allah Yang Maha Terpuji",
        "Allah Yang Maha Mengalkulasi (Menghitung Segala Sesuatu)",
        "Allah Yang Maha Memulai",
        "Allah Yang Maha Mengembalikan Kehidupan",
        "Allah Yang Maha Menghidupkan",
        "Allah Yang Maha Mematikan",
        "Allah Yang Maha Hidup",
        "Allah Yang Maha Mandiri",
        "Allah Yang Maha Penemu",
        "Allah Yang Maha Mulia",
        "Allah Yang Maha Tunggal",
        "Allah Yang Maha Esa",
        "Allah Yang Maha Dibutuhkan, Tempat Meminta",
        "Allah Yang Maha Menentukan, Maha Menyeimbangkan",
        "Allah Yang Maha Berkuasa",
        "Allah Yang Maha Mendahulukan",
        "Allah Yang Maha Mengakhirkan",
        "Allah Yang Maha Awal",
        "Allah Yang Maha Akhir",
        "Allah Yang Maha Nyata",
        "Allah Yang Maha Ghaib",
        "Allah Yang Maha Memerintah",
        "Allah Yang Maha Tinggi",
        "Allah Yang Maha Penderma (Maha Pemberi Kebajikan)",
        "Allah Yang Maha Penerima Tobat",
        "Allah Yang Maha Pemberi Balasan",
        "Allah Yang Maha Pemaaf",
        "Allah Yang Maha Pengasuh",
        "Allah Yang Maha Penguasa Kerajaan (Semesta)",
        "Allah Yang Maha Pemilik Kebesaran dan Kemuliaan",
        "Allah Yang Maha Pemberi Keadilan",
        "Allah Yang Maha Mengumpulkan",
        "Allah Yang Maha Kaya",
        "Allah Yang Maha Pemberi Kekayaan",
        "Allah Yang Maha Mencegah",
        "Allah Yang Maha Penimpa Kemudharatan",
        "Allah Yang Maha Memberi Manfaat",
        "Allah Yang Maha Pemberi Petunjuk",
        "Allah Yang Maha Pencipta Yang Tiada Bandingannya",
        "Allah Yang Maha Kekal",
        "Allah Yang Maha Pewaris",
        "Allah Yang Maha Pandai",
        "Allah Yang Maha Sabar"
    )

    val listAsmaulHusna : ArrayList<Data>
    get() {
        val listAsmaulHusna = arrayListOf<Data>()
        for (position in hijaiyah.indices){
            val data = Data(
                latin = hijaiyah[position],
                name = namaAsmaulHusna[position],
                terjemah = terjemahanAsmaulHusna[position]
            )
            listAsmaulHusna.add(data)
        }
        return listAsmaulHusna
    }
}